# Alternative local development setup for when Supabase (our primary database) is not required
# Use this only for basic development without Supabase Auth and other Supabase-specific features

services:
  shadcn-table:
    image: postgres:17.4
    restart: always
    container_name: shadcn-table
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data

volumes:
  postgres:
